name: Infra build and deployment 

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        options:
        - develop
        - master
permissions:
  contents: read
env:
  TF_LOG: INFO
  TF_INPUT: false
  
jobs: 
  pr-infra-check:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
          repository: TI-Tech-31/actions
          token: ${{ secrets.TTOKEN }}
          path:  infra
          ref: ${{ github.event.inputs.branch }}  # Use the branch provided from input
      

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform init
      id: init
      run: |
        
          cd /home/ssm-user/actions-runner/test_runner/TI-Tech-31/actions/terraform
          full_ref="${{ github.ref }}"
          branch_name=$(echo $full_ref | cut -d'/' -f 3)
          terraform init
          echo " Destination branch name is : $branch_name"
          if [[ "$branch_name" == "develop" ]]; then
            echo "Setting Terraform workspace to 'uat'"
            terraform workspace select uat || terraform workspace new uat
          elif [[ "$branch_name" == "master" ]]; then
            echo "Setting Terraform workspace to 'prod'"
            terraform workspace select prod || terraform workspace new prod
          else
            echo "Branch not supported for Terraform workspace selection"
            exit 1
          fi 

    # Run a terraform plan
    - name: Terraform plan
      id: plan
      continue-on-error: false
      run: |
          cd /home/runner/work/python_codes/python_codes/infra/terraform
          terraform plan  -out=myplan
          
  pr-infra-deploy:
  
    runs-on: ubuntu-latest
    environment: Approve
    permissions:
      id-token: write
      contents: read
        
    needs: pr-infra-check
   
    steps:   
    - name: Terraform Apply
      run: |
           cd /home/runner/work/python_codes/python_codes/infra/terraform/
           terraform apply -auto-approve -input=false myplan
